version: '3.0'
services:
  db: 
     image: mysql:5.7
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: minitwitdb
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always

  api:
    image: itudevopsgroupo/minitwit-backend:runtime
    build:
      context: ./minitwit-backend
    depends_on:
    - db
    ports:
    - "5050:5050"

volumes:
    dbdata: