name: Run Infer# Analysis

on:
  pull_request:
    branches: 
      - main
      
jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Build with dotnet
      run: dotnet build minitwit-backend/MiniTwit.sln
      
    - name: Run Infer#      
      uses: microsoft/infersharpaction@v1.4
      id: runinfersharp
      with:
        binary-path: MiniTwit

    - name: Infer# analysis results
      run: echo "${{ steps.runinfersharp.outputs.results }}"
      
